services:
  # Service for the Indexer

  base_images:
    build:
      context: ./base_images/rag_base # Path to base Dockerfile directory
      dockerfile: ./Dockerfile
    image: rag_base # Tag the image so other services can use it
    # Use 'docker-compose build base_rag_image_builder' to build it first

  indexer:
    build:
      context: .  
      dockerfile: ./indexer/Dockerfile 

    container_name: law_rag_indexer
    volumes:
      # Paths here are relative to the docker-compose.yml location (lawRAG2/)
      - ./chroma_db_storage:/app/chroma_db_storage
      - ./data/cases_2.jsonl:/app/data/cases_2.jsonl
      - ./.env:/app/.env
      - ./model_cache:/root/.cache/torch/sentence_transformers/
    restart: "no"

  # Service for the Retriever
  retriever:
    build:
      context: .  
      dockerfile: ./retriever/Dockerfile 
    container_name: law_rag_retriever
    volumes:
      # Paths here are relative to the docker-compose.yml location (lawRAG2/)
      - ./chroma_db_storage:/app/chroma_db_storage
      - ./.env:/app/.env
      - ./model_cache:/root/.cache/torch/sentence_transformers/
    restart: "on-failure"